version: '3.3'

services:
  flask:
    build: ./server/
    image: lotto-server
    ports:
      - "5000:5000"
  angular:
    build: ./client/mitolotto/
    image: lotto-client
    ports:
      - "3000:80"
